Added a choice for deletion of the local bin directory, to avoid dataloss during recompilation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,8 +12,20 @@ make
 rm -f -r *.o
 
 cd $CDIR
-rm -f -r bin
-mkdir bin
+
+if test -d bin; then
+  read -n1 -p 'A local bin directory already exists, do you wish to overwrite? (Y/N)' booleanYorN
+  case $booleanYorN in
+   y|Y) echo "" ; rm -f -r bin ; mkdir bin ;;
+   n|N) echo "" ; echo "only replacing binary files in local bin dir" ;;
+   *) echo "" ; echo "invalid Input "; exit 1 ;;
+  esac
+else 
+  mkdir bin
+fi
+
+
+
 
 mv $TMPDIR/rapsearch bin/rapsearch
 mv $TMPDIR/prerapsearch bin/
